bot/bot.go, bot/handlers.go, bot/interfaces.go, config/config.go, example_config.json, irc/irc.go, main.go, plugins/admin.go, slack/slack.go
Probably a bunch of bugs in here. Definitely not enough documentation. Deal with it. :sunglasses:
=> Slack integration

config/config.go, example_config.json, plugins/beers.go, slack/slack.go
A few database changes, nothing too major.
=> Fix untappd integration

plugins/counter.go
=> Fix number of fields for counter inventory

plugins/factoid.go
=> Change ID from nullable field to its value

bot/mock.go, config/config.go, example_config.json, main.go, plugins/babbler/babbler.go, plugins/babbler/babbler_test.go, slack/slack.go
PR/Merge for @skiesel's babbler.
=> Markov babbler plugin

plugins/reminder/reminder.go
=> Handle "remind me"

bot/bot.go, config/config.go, example_config.json
=> Add multiple command character support.

plugins/babbler/babbler.go, plugins/babbler/babbler_test.go
=> stk5's wish come true

plugins/counter/counter.go
=> This looks like += and -=

plugins/counter/counter.go, plugins/counter/counter_test.go
=> Add reset me command

plugins/babbler/babbler.go, plugins/babbler/babbler_test.go
@mccoyst always wants to be able to use phrases in the babbler. so here.
=> allow the babbler to be seeded with a full phrase

config/config.go, example_config.json, plugins/reminder/reminder.go, plugins/reminder/reminder_test.go
!remind msherms every 1h for 24h get a kit
=> batch adding of reminders for msherms

plugins/reminder/reminder.go, plugins/reminder/reminder_test.go
msherms brewed a beer, so we need to be able to call off the dogs, er, catbase.
=> cancel reminders

plugins/babbler/babbler.go, plugins/babbler/babbler_test.go, plugins/babbler/commands.go
Okay they're not new, but they're back!
The DB tables got changed around so you might want to just drop the old ones and we'll start fresh.
=> Some sexy new features

config/config.go, main.go, plugins/stats/stats.go, plugins/stats/stats_test.go
=> Stats plugin

plugins/babbler/babbler.go, plugins/babbler/babbler_test.go
1) Better syntax
2) Middle out
3) Small tweak to the babble bridging to possibly make it less deterministic
=> More babbler stuff

bot/handlers.go, bot/interfaces.go, bot/mock.go, irc/irc.go, main.go, plugins/emojifyme/emojifyme.go, slack/slack.go
Parse incoming messages to see if we can do emoji replacements for words
=> Ready... Set... EmojifyMe.

config/config.go, example_config.json, plugins/your/your.go, plugins/your/your_test.go
Specify replacements in the config file
=> Your refactor

config/config.go, example_config.json, plugins/reaction/reaction.go
Fix probability of generating a reaction so that it matches better with the spirit of the config value
=> Fix Probabilities

bot/interfaces.go, irc/irc.go, main.go, slack/slack.go
slack: don't fatal on EOF, reconnect
irc: don't fatal, just return error
=> bot: change serve() to return an error

config/config.go, main.go, plugins/twitch/twitch.go, plugins/twitch/webTemplate.go
* Added OAuth abilities
* Added full API spec for endpoint response
* Use net/url to build request
=> twitch: update to current API

bot/bot.go, bot/handlers.go, bot/interfaces.go, bot/mock.go, config/config.go, main.go, plugins/inventory/inventory.go, slack/slack.go
=> inventory: initial sketch

plugins/beers/beers.go
* Added all image formats to checkin structure
* Changed which image is selected for display in the channel
=> beers: make untappd icons square

plugins/fact/factoid.go
* Added datatype for aliases
* Added table for aliases
* Added resolving mechanism after factoid miss
=> factoid: learn and spit out aliases

slack/fix_text.go, slack/slack.go
* Removed emoji conversion from chat
* Added bool to getUser
* Fixed getUser references
=> slack: import velour/chat parsing

plugins/fact/factoid.go
* No circular aliases may be created
* Must have a resolvable destination
=> fact: add protection for aliases

plugins/babbler/babbler.go
The version changed or something and tables weren't being created.
=> babbler: create tables no matter what

bot/bot.go, bot/handlers.go, bot/interfaces.go, bot/mock.go, irc/irc.go, main.go, plugins/admin/admin.go, plugins/babbler/babbler.go, plugins/beers/beers.go, plugins/counter/counter.go, plugins/dice/dice.go, plugins/downtime/downtime.go, plugins/emojifyme/emojifyme.go, plugins/fact/factoid.go, plugins/fact/remember.go, plugins/first/first.go, plugins/inventory/inventory.go, plugins/leftpad/leftpad.go, plugins/reaction/reaction.go, plugins/reminder/reminder.go, plugins/rpgORdie/rpgORdie.go, plugins/rpgORdie/rpgORdie_test.go, plugins/rss/rss.go, plugins/stats/stats.go, plugins/talker/talker.go, plugins/twitch/twitch.go, plugins/your/your.go, plugins/zork/zork.go, slack/slack.go
Just to get the responses and edits and all that into mainline
=> RPG or DIEEEEEEEEEEEE

config/config.go, slack/slack.go
grab the bot's bot id from the message response and use that to avoid self-reply loops
=> allow more bot2bot

config/config.go, example_config.lua, plugins/emojifyme/emojifyme.go
=> Emojifyme signal enhancement for eaburns and me

plugins/reminder/reminder.go, plugins/reminder/reminder_test.go
Jag har implementerat funktionaliteten för att lista påminnelser till en användare och från en användare som använder syntaxen "!list reminders from seabass" och "!list reminders to seabass"
=> Listing Reminders "to" or "from" a user

main.go, plugins/couldashouldawoulda/csw.go, plugins/couldashouldawoulda/csw_test.go
(Sorry about the last one, it didn't get set off of master)
=> This might be entertaining on occasion

plugins/reminder/reminder.go, plugins/reminder/reminder_test.go
No YOU made a bad code change.
=> reminder: you for real this time

plugins/nerdepedia/nerdepedia.go
But seriously, double unescaping.
=> I'll see your double escaping, and raise you triple unescaping. 

.travis.yml, gok.sh, plugins/babbler/babbler.go, plugins/babbler/babbler_test.go, plugins/babbler/commands.go, plugins/beers/beers_test.go, plugins/emojifyme/emojifyme.go, plugins/nerdepedia/nerdepedia.go, plugins/reminder/reminder_test.go, plugins/zork/zork.go
Travis actually checks stuff now! 🎉
=> Testcleanup

bot/bot.go, config/config.go, config/config_test.go, config/defaults.go, irc/irc.go, main.go, plugins/admin/admin.go, plugins/admin/admin_test.go, plugins/beers/beers.go, plugins/downtime/downtime.go, plugins/emojifyme/emojifyme.go, plugins/fact/factoid.go, plugins/first/first.go, plugins/inventory/inventory.go, plugins/leftpad/leftpad.go, plugins/leftpad/leftpad_test.go, plugins/reaction/reaction.go, plugins/reminder/reminder.go, plugins/rpgORdie/rpgORdie.go, plugins/sisyphus/sisyphus.go, plugins/twitch/twitch.go, plugins/twitch/twitch_test.go, plugins/your/your.go, slack/slack.go, version.go
See if this does it for you, @skiesel
=> Configdefault

plugins/admin/admin.go
This will not silence any out of band messages such as Untappd checks,
Twitch notifications, or the startup message.
This will cause catbase not to know anything about the conversation,
which means quoting something during the quiet period is impossible.
Everything during quiet time is off the record.
=> admin: be quiet

connectors/slackapp/slackApp.go
Because that just fucking works.
=> slack: revert to manual slack call for replies

plugins/twitch/twitch.go
And fun. Now they're templates.
=> twitch: make stream announcements more complicated

bot/handlers.go, plugins/twitch/twitch.go
* Also fix twitch's help registration and message
=> help: fix the help system after I borke it

plugins/beers/beers.go
Just another problem like remember had.
=> beers: fix bad indirection issue

.gitignore, connectors/slackapp/slackApp.go, main.go
* Turned stack trace on for Errs
* Turned file trace on for all logs
* Added error where a panic was detected earlier in the day
* Added `run.sh` to ignore
=> logging: update configuration

bot/interfaces.go, connectors/irc/irc.go, connectors/slackapp/slackApp.go, plugins/beers/beers.go
* Make untappd checkins embed images
* Added attachment types as an optional send arg
=> slack: add image support

bot/msg/message.go, connectors/slackapp/slackApp.go, plugins/first/first.go
And be sure not to pay attention to private/direct messages
=> first: change to per channel

connectors/slackapp/slackApp.go
* Remove entry log lines
* Change topic format for pisg support
=> slackApp: nicen logs a bit

bot/web.go, plugins/cli/index.go
* menuize front page
* fix url bug
* fix cli
=> web: bugfix pack

bot/bot.go, bot/interfaces.go, bot/mock.go, plugins/admin/admin.go, plugins/cli/cli.go, plugins/cli/index.go, plugins/counter/counter.go, plugins/counter/html.go
* Applies for services that modify data
* Anybody in the slack can ask for the daily secret
=> web: use secret instead of human test

go.mod, go.sum, main.go, plugins/newsbid/newsbid.go, plugins/newsbid/webshit/webshit.go, plugins/newsbid/webshit/webshit_test.go
Bid on HN articles against what n-gate decides to write about.
=> Webshit: a game

plugins/newsbid/newsbid.go, plugins/newsbid/webshit/webshit.go
* No more negative scores
* Winners divide all points based on their bets
=> newsbid: divide all bids amongst winners

.github/workflows/go.yml
Probably won't work. Expect 20,000 PRs that I mere myself instead of just unprotecting the master branch like a smart person.
=> github: Enable GH Workflows

connectors/slackapp/slackApp.go
...again. Just had to turn the e-brake off and flip an equality.
=> slackApp: fix user detection

go.mod, go.sum, plugins/reaction/reaction.go
The harass stuff may come back later.
Also, the sentiment model only has two classes and is trained on the IMDB dataset. That's really not ideal for what I have in mind, but I think it can be expanded later. We don't yet have enough data to train our own model in any meaningful way.
=> reaction: add sentiment analysis; remove harass

plugins/beers/beers.go
Note: this may not work on the first try. I'm not going to sit around
waiting for a badged checkin in #test.
=> untappd: add badge support

plugins/beers/beers.go
Checking out a reorder of the args too.
=> untappd: switch text line for image descriptions

plugins/zork/zork.go
zork: squash pkgPath err
zork: add flag support
=> zork: make path to exec and dat configurable

go.mod, go.sum, main.go, plugins/twitter/twitter.go
=> twitter: add plugin

plugins/fuck/fuck.go
* verify instruction limit setting
* truncate output buffer
=> fuck: stop he-who-must-not-be-named's antics

config/config.go, plugins/admin/admin.go, plugins/git/git.go, plugins/git/gitea.go
Also added an `!unset` command for configurations.
=> git: add nicer repo addition & gitea support

plugins/picker/picker.go, plugins/picker/picker_test.go
* simplified picking regex
* added test case for previously broken message
=> pick: fix broken pick

bot/handlers.go
* $time: a made up time
* $now: current time
* $msg: the user's message
=> bot: add new variables

plugins/fact/factoid.go
This will attach the last URL it sees as an image attachment. It will
fail if that is not a valid image (IDK, slack will get mad) and if no
image is found, it will send as text. The text in the message that is
not a URL will be sent as the image title.
=> fact: add image verb

plugins/admin/admin.go
* you can now run `push <setting> <value>` to add values to a setting
=> config: add push command

plugins/newsbid/newsbid.go, plugins/newsbid/webshit/webshit.go
Oops. That's what I get for live coding.
=> Sort scores

plugins/counter/counter.go, plugins/twitter/twitter.go
* Also remove a %w causing warnings
=> twitter: stop trying to filter RTs

.gitignore, go.mod, go.sum, plugins/meme/meme.go, plugins/talker/talker.go
Also clean up memory sometimes.
=> meme: make messages commands

plugins/sms/sms.go
=> sms: add help text

bot/bot.go, bot/handlers.go, bot/interfaces.go, bot/mock.go, plugins/admin/admin.go
admin: use 'enable/disable plugin <name>'
=> bot: add ability to disable plugins per channel

main.go, plugins/countdown/countdown.go, plugins/countdown/countdown_test.go
=> countdown: add NYE countdown

plugins/reaction/naive_bayes.go, plugins/reaction/reaction.go, util/eval_emojy/main.go, util/learn_emojy/main.go
Ship it.
This shouldn't actually change anything as the default confidence has to be higher than the model can support right now.
=> reaction: add emojy language model

config/config.go, plugins/meme/meme.go, plugins/meme/web.go, plugins/meme/webHandlers.go
=> meme: add web config

plugins/newsbid/newsbid.go, plugins/newsbid/webshit/hn/api.go, plugins/newsbid/webshit/webshit.go
=> newsbid: update for season 2

plugins/meme/meme.go, plugins/meme/webHandlers.go
=> meme: add capitalization to configs, true default

plugins/meme/web.go
This updates the web view to provide a screen to edit any particular
config in a text area, update the image URL, and remove a meme.
fixes #330
=> meme: add config and delete

connectors/slackapp/slackApp.go
This might solve the thing slack has been yapping about non-stop for months.
=> slackApp: convert from channel to conversation

plugins/achievements/achievements.go, plugins/achievements/achievements_test.go
=> achievements: refactor

plugins/admin/admin.go, plugins/admin/admin_test.go
=> Refactor admin

plugins/aoc/aoc.go
=> aoc: refactor

plugins/gpt2/gpt2.go
=> gpt2: refactor

bot/bot.go, bot/handlers.go, bot/interfaces.go, bot/mock.go, plugins/babbler/babbler.go, plugins/babbler/babbler_test.go, plugins/babbler/commands.go
=> babbler: refactor

plugins/beers/beers.go, plugins/beers/beers_test.go
=> Refactor beers

plugins/dice/dice.go, plugins/dice/dice_test.go
=> dice: refactor

plugins/couldashouldawoulda/csw.go, plugins/couldashouldawoulda/csw_test.go
=> csw: refactor

bot/interfaces.go, connectors/discord/discord.go, plugins/first/first.go
=> first: refactor and add clear command

plugins/git/git.go
=> git: refactor

plugins/inventory/inventory.go
=> inventory: refactor and fix regexes

bot/interfaces.go, plugins/goals/goals.go
=> goals: refactor

plugins/impossible/impossible.go, plugins/impossible/impossible_test.go
=> impossible: refactor

plugins/leftpad/leftpad.go, plugins/leftpad/leftpad_test.go
=> leftpad: refactor

plugins/impossible/impossible.go, plugins/meme/meme.go
Ref #346 
impossible: fix bug where it was eating all messages
=> meme: refactor

plugins/nerdepedia/nerdepedia.go, plugins/nerdepedia/nerdepeida_test.go
=> refactor: nerdepedia the lazy way

plugins/meme/meme.go, plugins/meme/webHandlers.go
* Moved meme generation to the URL service
* URLs now contain the meme configurations
* Cached by config (expires with bot restart)
Fixes #371
=> meme: memes generated at request time

plugins/picker/picker.go, plugins/picker/picker_test.go
=> picker: refactor

plugins/reaction/reaction.go
=> reaction: refactor

plugins/remember/remember.go, plugins/remember/remember_test.go
=> remember: refactor

main.go, plugins/giphy/giphy.go
=> giph: add plugin

plugins/your/your.go, plugins/your/your_test.go
=> your: refactor

util/files/main.go
I think it works good enough to cron job now.
=> files: update deletion script

bot/interfaces.go, connectors/discord/discord.go, connectors/irc/irc.go, connectors/slack/slack.go, connectors/slackapp/slackApp.go, plugins/cli/cli.go, plugins/last/last.go
This
* ensures the last is between yesterday and yesterday
* adds a channel check to the query
* adds a command to check a specific channel
=> last: add multichannel support

config/config.go, main.go, plugins/rest/rest.go, plugins/secrets/secrets.go, plugins/secrets/web.go
Also modify rest to use secrets plugin
=> secrets: add plugin

plugins/beers/beers.go, plugins/beers/beers_test.go, plugins/counter/counter.go, plugins/goals/goals.go
This is probably broken, but I'll test it in prod.
=> goals: fix default channel reporting

plugins/first/first.go
This should prevent Slack's scheduled messages from gaming first
=> first: add configurable jitter

plugins/rest/rest.go
Adding a custom parser for GPT-2 queries because it's easier this way.
=> rest: bypass jq when it's convenient

bot/index.html, plugins/admin/apppass.html, plugins/admin/vars.html, plugins/cli/index.html, plugins/counter/index.html, plugins/fact/index.html, plugins/meme/index.html, plugins/secrets/index.html
3.x came out and @latest busted everything.
=> web: fix vue version references

connectors/discord/discord.go, go.mod, go.sum, main.go, plugins/emojy/emojy.go, plugins/emojy/index.html, plugins/emojy/web.go
- added reaction type and event for discord connectors
- added web page to view emojy usage
- added new table for counting emojy
=> emojy: create plugin

bot/handlers.go, bot/msg/message.go, connectors/discord/discord.go, connectors/irc/irc.go, connectors/slackapp/slackApp.go, plugins/fact/fact.go, plugins/fact/factoid.go, plugins/fact/web.go
- factoid is a mess, but I at least split it into a few parts
- need to move config values from factoid to fact
- need to rename the whole thing to fact
- probably need to go over it with a fine toothed comb
- 5 seconds, why 5 seconds? I still don't know
- added kind to the message type so we can filter reactions out
=> factoid: refactor and ignore reaction

.gitignore, go.sum, plugins/emojy/emojy.go, plugins/emojy/index.html, plugins/emojy/web.go
- record emojy as timestamped log instead of a count
=> emojy: redo database schema

go.mod, go.sum, plugins/emojy/emojy.go, plugins/emojy/index.html, plugins/emojy/web.go
- show custom emojy
- categorize by source type
- record emojy used in messages
=> emojy: make the web page nicer

bot/handlers.go, bot/interfaces.go, bot/mock.go, connectors/discord/discord.go, connectors/irc/irc.go, connectors/slackapp/slackApp.go, go.mod, go.sum, plugins/cli/cli.go, plugins/emojifyme/emojifyme.go, plugins/emojy/emojy.go, plugins/emojy/index.html, plugins/emojy/web.go
- includes a web interface for uploading new images
- includes a web interface for viewing 'possible' images
=> emojy: allow creation and removal of emojy

go.mod, go.sum, plugins/counter/api.go
=> add rate limit middleware

bot/bot.go, plugins/admin/admin.go, plugins/first/first.go, plugins/roles/roles.go
This was a pretty big security/bug that I have just not felt like fixing for ages.
=> Admin hole

bot/bot.go, config/config.go, plugins/secrets/secrets.go, plugins/twitch/twitch.go
- refactored secrets to be in config
- added missing format string to bot
=> twitch: add reauthentication

connectors/discord/discord.go, go.mod, go.sum, main.go, plugins/twitch/bridge.go, plugins/twitch/irc.go, plugins/twitch/twitch.go, plugins/twitch/twitch_test.go
* Should connect a bridge to streamer's channel any time a stream starts
* Should disconnect when stream ends
* Add `track` and `untrack` commands to manually modify bridge
* Adds support for creating Discord threads
=> twitch: Add IRC-Discord bridge

bot/interfaces.go, connectors/discord/discord.go, plugins/meme/meme.go
* Added File handling to Discord mesasges
=> meme: changed to file upload instead of embed

connectors/discord/discord.go, main.go, plugins/llm/gemini.go, plugins/talklikeapirate/pirate.go, plugins/tldr/tldr.go
=> talklikeapirate: we just went nucular

connectors/irc/irc.go, go.mod, go.sum, plugins/countdown/countdown.go, plugins/reminder/reminder.go, plugins/twitch/irc.go
Also updated some logging that was busted.
=> countdown: accept y/M/d as year, "month", and day
